In [79]:
print("helo")
import pandas as pd
import numpy as np

helo

In [80]:
dict1={
    'name':['nikhil',"harshit","gaurav","ravi"],
    "marks":[53,43,54,93],
    "city": ["ramnagar","palampur","gopalpur","laknour pind"]
}

In [81]:
# df = pd.DataFrame(dict1)

In [82]:
# df

In [83]:
# df.to_csv('friends.csv')
# if i dont want index
# df.to_csv('friend.csv',index=False)

In [84]:
# df.head(2)

In [85]:
# df.tail(2)

In [86]:
# df.describe()

In [87]:
# import pandas as pd 

# new = pd.read_csv('annual.csv')
# new

In [88]:
import pandas as pd 

new = pd.read_csv('annual.csv')

In [89]:

ser = pd.Series(np.random.rand(67))
ser

0     0.997394
1     0.244348
2     0.423185
3     0.488983
4     0.833957
        ...
62    0.396871
63    0.724481
64    0.373742
65    0.441799
66    0.179839
Length: 67, dtype: float64

In [90]:
helo = pd.DataFrame(np.random.rand(334,5),index=np.arange(334))
helo

            0         1         2         3         4
0    0.394836  0.747785  0.012294  0.504465  0.372681
1    0.494620  0.404607  0.027123  0.885269  0.556611
2    0.270592  0.461370  0.081605  0.777141  0.375585
3    0.810699  0.298797  0.378748  0.211710  0.458697
4    0.217952  0.530772  0.772177  0.686854  0.082714
..        ...       ...       ...       ...       ...
329  0.399982  0.360141  0.356234  0.385250  0.405778
330  0.434640  0.244103  0.432786  0.596441  0.442565
331  0.474092  0.519595  0.988690  0.293177  0.681703
332  0.927395  0.485241  0.674966  0.330500  0.354539
333  0.191716  0.617087  0.156194  0.340164  0.588155

[334 rows x 5 columns]

In [91]:
''' if you want to make really change in your data
use name of data like this 
helo=helo.drop(1,axis=0)
and if you only want to see result of your fxn 
helo.drop(1,axis=1)'''

' if you want to make really change in your data\nuse name of data like this \nhelo=helo.drop(1,axis=0)\nand if you only want to see result of your fxn \nhelo.drop(1,axis=1)'

In [92]:
helo = pd.DataFrame(np.random.rand(334,5),index=np.arange(334))
helo

            0         1         2         3         4
0    0.209947  0.212874  0.195907  0.566854  0.259475
1    0.231538  0.526540  0.603013  0.769968  0.977124
2    0.007004  0.579617  0.678379  0.617008  0.903729
3    0.175026  0.743498  0.718016  0.961959  0.043158
4    0.912382  0.768803  0.032796  0.606583  0.307337
..        ...       ...       ...       ...       ...
329  0.095899  0.783806  0.426778  0.792955  0.602780
330  0.645430  0.183102  0.098019  0.261873  0.654092
331  0.124546  0.997863  0.257665  0.790433  0.775256
332  0.739368  0.565170  0.753313  0.948159  0.877091
333  0.306660  0.908267  0.524861  0.050481  0.097988

[334 rows x 5 columns]

In [93]:
type(helo)
helo.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [94]:
helo[1][1]='nikhil'
helo.dtypes
helo

C:\Users\user\AppData\Local\Temp\ipykernel_6156\185899151.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  helo[1][1]='nikhil'
C:\Users\user\AppData\Local\Temp\ipykernel_6156\185899151.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nikhil' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  helo[1][1]='nikhil'

            0         1         2         3         4
0    0.209947  0.212874  0.195907  0.566854  0.259475
1    0.231538    nikhil  0.603013  0.769968  0.977124
2    0.007004  0.579617  0.678379  0.617008  0.903729
3    0.175026  0.743498  0.718016  0.961959  0.043158
4    0.912382  0.768803  0.032796  0.606583  0.307337
..        ...       ...       ...       ...       ...
329  0.095899  0.783806  0.426778  0.792955  0.602780
330  0.645430  0.183102  0.098019  0.261873  0.654092
331  0.124546  0.997863  0.257665  0.790433  0.775256
332  0.739368   0.56517  0.753313  0.948159  0.877091
333  0.306660  0.908267  0.524861  0.050481  0.097988

[334 rows x 5 columns]

In [95]:
helo.to_numpy()

array([[0.2099471942613843, 0.2128743115098548, 0.19590673444894013,
        0.5668535920732312, 0.2594747507828393],
       [0.23153830274588172, 'nikhil', 0.6030130474454821,
        0.7699684065859453, 0.9771237006027012],
       [0.00700370034144604, 0.5796174215405432, 0.6783790873329505,
        0.6170083395542761, 0.9037294375309727],
       ...,
       [0.12454602600162945, 0.9978630618361264, 0.257665100224578,
        0.790433289161368, 0.7752555944964591],
       [0.7393678559916429, 0.5651696353649873, 0.7533125642450972,
        0.9481586693495421, 0.8770906231174911],
       [0.3066597226335054, 0.9082667200298525, 0.5248613741867353,
        0.050480628577979414, 0.09798846793921623]], dtype=object)

In [96]:
helo[1][1]=0.35

In [97]:
helo.T#t for transpose

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.209947,0.231538,0.007004,0.175026,0.912382,0.939086,0.538772,0.091868,0.034118,0.360702,...,0.37178,0.430596,0.325242,0.884995,0.289203,0.095899,0.64543,0.124546,0.739368,0.30666
1,0.212874,0.35,0.579617,0.743498,0.768803,0.704524,0.42908,0.665709,0.417181,0.838111,...,0.259854,0.13745,0.591573,0.60852,0.403584,0.783806,0.183102,0.997863,0.56517,0.908267
2,0.195907,0.603013,0.678379,0.718016,0.032796,0.116333,0.976935,0.367479,0.623311,0.487502,...,0.742808,0.48275,0.66166,0.316294,0.967721,0.426778,0.098019,0.257665,0.753313,0.524861
3,0.566854,0.769968,0.617008,0.961959,0.606583,0.797485,0.585006,0.584769,0.282577,0.604082,...,0.107229,0.531459,0.006371,0.850189,0.165489,0.792955,0.261873,0.790433,0.948159,0.050481
4,0.259475,0.977124,0.903729,0.043158,0.307337,0.144252,0.230324,0.727588,0.714905,0.445468,...,0.993436,0.002787,0.915814,0.324303,0.826466,0.60278,0.654092,0.775256,0.877091,0.097988

In [98]:
helo.head()

          0         1         2         3         4
0  0.209947  0.212874  0.195907  0.566854  0.259475
1  0.231538      0.35  0.603013  0.769968  0.977124
2  0.007004  0.579617  0.678379  0.617008  0.903729
3  0.175026  0.743498  0.718016  0.961959  0.043158
4  0.912382  0.768803  0.032796  0.606583  0.307337

In [99]:
helo.sort_index(axis=1,ascending=False)

            4         3         2         1         0
0    0.259475  0.566854  0.195907  0.212874  0.209947
1    0.977124  0.769968  0.603013      0.35  0.231538
2    0.903729  0.617008  0.678379  0.579617  0.007004
3    0.043158  0.961959  0.718016  0.743498  0.175026
4    0.307337  0.606583  0.032796  0.768803  0.912382
..        ...       ...       ...       ...       ...
329  0.602780  0.792955  0.426778  0.783806  0.095899
330  0.654092  0.261873  0.098019  0.183102  0.645430
331  0.775256  0.790433  0.257665  0.997863  0.124546
332  0.877091  0.948159  0.753313   0.56517  0.739368
333  0.097988  0.050481  0.524861  0.908267  0.306660

[334 rows x 5 columns]

In [100]:
helo.sort_index(axis=0,ascending=False)

            0         1         2         3         4
333  0.306660  0.908267  0.524861  0.050481  0.097988
332  0.739368   0.56517  0.753313  0.948159  0.877091
331  0.124546  0.997863  0.257665  0.790433  0.775256
330  0.645430  0.183102  0.098019  0.261873  0.654092
329  0.095899  0.783806  0.426778  0.792955  0.602780
..        ...       ...       ...       ...       ...
4    0.912382  0.768803  0.032796  0.606583  0.307337
3    0.175026  0.743498  0.718016  0.961959  0.043158
2    0.007004  0.579617  0.678379  0.617008  0.903729
1    0.231538      0.35  0.603013  0.769968  0.977124
0    0.209947  0.212874  0.195907  0.566854  0.259475

[334 rows x 5 columns]

In [101]:
helo[1]

0      0.212874
1          0.35
2      0.579617
3      0.743498
4      0.768803
         ...
329    0.783806
330    0.183102
331    0.997863
332     0.56517
333    0.908267
Name: 1, Length: 334, dtype: object

In [102]:
type(helo[1])

pandas.core.series.Series

In [103]:
# helo2=helo  #this is view if you change something here also changed in helo
# helo2[1][1]=0.78
# helo

In [104]:
#methods of copying 
# if you change something in helo2 it will not change helo
# helo2=helo[:]
# helo2=helo.copy()
# helo2[1][1]=0.45
# helo
# helo2

In [105]:
# helo2

In [106]:
#use loc for changing 
helo.loc[1][1]=0.12
helo.loc[5,5]=0.676
helo

C:\Users\user\AppData\Local\Temp\ipykernel_6156\118242524.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  helo.loc[1][1]=0.12

            0         1         2         3         4   5
0    0.209947  0.212874  0.195907  0.566854  0.259475 NaN
1    0.231538      0.35  0.603013  0.769968  0.977124 NaN
2    0.007004  0.579617  0.678379  0.617008  0.903729 NaN
3    0.175026  0.743498  0.718016  0.961959  0.043158 NaN
4    0.912382  0.768803  0.032796  0.606583  0.307337 NaN
..        ...       ...       ...       ...       ...  ..
329  0.095899  0.783806  0.426778  0.792955  0.602780 NaN
330  0.645430  0.183102  0.098019  0.261873  0.654092 NaN
331  0.124546  0.997863  0.257665  0.790433  0.775256 NaN
332  0.739368   0.56517  0.753313  0.948159  0.877091 NaN
333  0.306660  0.908267  0.524861  0.050481  0.097988 NaN

[334 rows x 6 columns]

In [107]:
# you can change colums
#  helo.columns=list('abcde') 
# helo

In [108]:
# axis 0 means = row 
# axis 1 means = colomns
# if you dont give axis it will remove from row


# to drop series 
# use drop fxn
# like this 
# helo.drop(5)
helo=helo.drop(5,axis=1)

#like this

In [109]:
helo

            0         1         2         3         4
0    0.209947  0.212874  0.195907  0.566854  0.259475
1    0.231538      0.35  0.603013  0.769968  0.977124
2    0.007004  0.579617  0.678379  0.617008  0.903729
3    0.175026  0.743498  0.718016  0.961959  0.043158
4    0.912382  0.768803  0.032796  0.606583  0.307337
..        ...       ...       ...       ...       ...
329  0.095899  0.783806  0.426778  0.792955  0.602780
330  0.645430  0.183102  0.098019  0.261873  0.654092
331  0.124546  0.997863  0.257665  0.790433  0.775256
332  0.739368   0.56517  0.753313  0.948159  0.877091
333  0.306660  0.908267  0.524861  0.050481  0.097988

[334 rows x 5 columns]

In [110]:
helo.loc[[1],:] # for accessing rows , you can give multiple rows and columns

          0     1         2         3         4
1  0.231538  0.35  0.603013  0.769968  0.977124

In [111]:
helo.loc[:,[1]]# for accessing coulms

            1
0    0.212874
1        0.35
2    0.579617
3    0.743498
4    0.768803
..        ...
329  0.783806
330  0.183102
331  0.997863
332   0.56517
333  0.908267

[334 rows x 1 columns]

In [112]:
#complex query
helo.loc[(helo[0]<0.3)]
#this tels where is value less tham 0.3

            0         1         2         3         4
0    0.209947  0.212874  0.195907  0.566854  0.259475
1    0.231538      0.35  0.603013  0.769968  0.977124
2    0.007004  0.579617  0.678379  0.617008  0.903729
3    0.175026  0.743498  0.718016  0.961959  0.043158
7    0.091868  0.665709  0.367479  0.584769  0.727588
..        ...       ...       ...       ...       ...
315  0.194034  0.512191  0.245398  0.015967  0.009527
322  0.058431   0.39049  0.705516  0.800881  0.208464
328  0.289203  0.403584  0.967721  0.165489  0.826466
329  0.095899  0.783806  0.426778  0.792955  0.602780
331  0.124546  0.997863  0.257665  0.790433  0.775256

[111 rows x 5 columns]

In [113]:
helo.loc[(helo[0]<0.3) &(helo[1]<0.1)]

            0         1         2         3         4
36   0.116241  0.042128  0.880767  0.343561  0.722319
136  0.046496  0.069575  0.631830  0.275647  0.337177
176  0.023049  0.059438  0.317014  0.271825  0.906395
193  0.056170  0.036314  0.827655  0.890847  0.962362
304  0.008373  0.087649  0.606951  0.046114  0.742353

In [114]:
helo.iloc[0,4]
# if you want to print from index number use iloc this otherwise use loc

np.float64(0.2594747507828393)

In [115]:
helo.loc[[1],[4]]
# in this way you can print value by name of columns and row

          4
1  0.977124

In [116]:
helo.iloc[[0,4],[0,3]]

          0         3
0  0.209947  0.566854
4  0.912382  0.606583

In [117]:
ser=[1,2,3,4,45,45,17,12,34]
h=[r for r in ser if r>10]
print(h)

[45, 45, 17, 12, 34]

In [118]:
h=[d for d in range(1,100) if d>10]
print(h)

[11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]

In [119]:
for i in range(1,34):
    if i>10 and i<25:
        print(i)

11
12
13
14
15
16
17
18
19
20
21
22
23
24

In [120]:
ser=pd.Series([51,39,54,76,57,67,56,32,45,87,45,3,45,56,67,76])
type(ser)

pandas.core.series.Series

In [121]:
# h=[r for r in ser if r>40]
# h

In [122]:
# type(h)

In [123]:
# h[::-1]

In [124]:
ser[ser>40]

0     51
2     54
3     76
4     57
5     67
6     56
8     45
9     87
10    45
12    45
13    56
14    67
15    76
dtype: int64

In [125]:

n=[51, 54, 76, 57, 67, 56, 45, 87, 45, 45, 56, 67, 76]

In [126]:
m=pd.Series(n)

In [127]:
m

0     51
1     54
2     76
3     57
4     67
5     56
6     45
7     87
8     45
9     45
10    56
11    67
12    76
dtype: int64

In [128]:
m.max()

np.int64(87)

In [129]:
m.loc[m<50]=60
m

0     51
1     54
2     76
3     57
4     67
5     56
6     60
7     87
8     60
9     60
10    56
11    67
12    76
dtype: int64

In [130]:
a=pd.Series([1,3,4,5,6,3,5,7])
b=pd.Series([4,5,7,8,2,4,3,4])

In [131]:
a*b

0     4
1    15
2    28
3    40
4    12
5    12
6    15
7    28
dtype: int64

In [132]:
d=pd.Series({'apple':50,'banana':80,'cherry':200})
d

apple      50
banana     80
cherry    200
dtype: int64

In [133]:
d.keys()

Index(['apple', 'banana', 'cherry'], dtype='object')

In [134]:
(d.values)

array([ 50,  80, 200])

In [135]:
'banana' in d.values

False

In [136]:
'banana'in d.keys()

True

In [137]:
ser1=pd.Series([12,34,44,None],index=[3,2,1,4])

In [138]:
ser1.fillna('not found')

3         12.0
2         34.0
1         44.0
4    not found
dtype: object

In [139]:
ser2=pd.Series([range(5,61,5)])
ser2
type(ser2)

pandas.core.series.Series

In [140]:
def check(n):
    if n%2==0:
     return('Even')
    else:
      return ('odd')

In [141]:
res=ser1.apply(check)
res

3    Even
2    Even
1    Even
4     odd
dtype: object

In [142]:
r=pd.Series([12,34,45,66,35,87,11,23,32,43,65,89])

In [143]:
r[(r>40)&(r<80)]

2     45
3     66
9     43
10    65
dtype: int64

In [144]:
r[r.between(40,80,inclusive='neither')]

2     45
3     66
9     43
10    65
dtype: int64

In [145]:
even=r[r%2==0]
print(even)

0    12
1    34
3    66
8    32
dtype: int64

In [146]:
r.idxmax()

11

In [147]:
r.loc[r>30]=0
r

0     12
1      0
2      0
3      0
4      0
5      0
6     11
7     23
8      0
9      0
10     0
11     0
dtype: int64

In [148]:
r.mean().round()

np.float64(4.0)

In [149]:
t=pd.Series([12,34,4,5,45,67,90,80,45,90,32,30,10,56,30])

In [150]:
t[(t%2==0)&(t%5==0)]

6     90
7     80
9     90
11    30
12    10
14    30
dtype: int64

In [151]:
# t.loc[t>50]='high'
# t

In [152]:
t[t%2==0].sum()

np.int64(468)

In [153]:
t**2

0      144
1     1156
2       16
3       25
4     2025
5     4489
6     8100
7     6400
8     2025
9     8100
10    1024
11     900
12     100
13    3136
14     900
dtype: int64

In [154]:
t[t>30].index

Index([1, 4, 5, 6, 7, 8, 9, 10, 13], dtype='int64')